# Generated by Django 4.2 on 2023-07-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_contactphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
    ]
